apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
      app: anji
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: anji
  ports:
    - port: 80
      targetPort: 8080
